export { computeCompatibility } from './engine'
export { registerCriterion, getCriterion, getAllCriteria, resetCriteriaForTesting } from './registry'
export { communicationCriterion } from './criteria/communication'
export { valuesCriterion } from './criteria/values'
export { interestsCriterion } from './criteria/interests'
export { lifestyleCriterion } from './criteria/lifestyle'
export { availabilityCriterion } from './criteria/availability'
export { goalsCriterion } from './criteria/goals'
export type * from './types'
